@startuml
actor Directeur
actor Enseignant
participant "Système Cours" as SC
participant "Module Validation" as MV
participant "Module Disponibilité" as MD
participant "Planning des cours" as PL

Directeur -> SC: Saisir infos cours
SC -> MV : Vérifier la saisie
MV --> SC: Résultat validation

SC -> MD : Vérifier disponibilité professeur
MD --> SC : Résultat disponibilité

alt Professeur disponible
    SC -> Enseignant : Notification nouveau cours
    SC -> PL : Ajouter cours au planning
    SC --> Directeur : Confirmation création
else
    SC --> Directeur : Message erreur (prof indisponible)
end


@enduml