@startuml
'https://plantuml.com/use-case-diagram
left to right direction

:Teacher : as Teacher
:Student : as Student
:Director : as Director

package View{
:Teacher: --> (consulter les élèves)
:Teacher: --> (consulter les cours)
:Student: --> (consulter les cours)
}
package Manage{
    :Director: --> (gérer les enseignants)
    :Director: --> (gérer les élèves)
    :Director: --> (gérer les cours)
    (gérer les enseignants) --> (gérer les adresses) : <<extend>>
    (gérer les élèves) --> (gérer les adresses) : <<extend>>

}
@enduml