@startuml
'https://plantuml.com/use-case-diagram

:Teacher : as Teacher
:Student : as Student


package System{

(gérer les élèves) --> (ajouter un élève)
(gérer les élèves) --> (supprimer un élève)
(gérer les élèves) --> (modifier un élève)
(gérer les élèves) --> (afficher un élève)

(gérer les enseignants) --> (ajouter un enseignant)
(gérer les enseignants) --> (supprimer un enseignant)
(gérer les enseignants) --> (modifier un enseignant)
(gérer les enseignants) --> (afficher un enseignant)

(gérer les cours) --> (ajouter un cours)
(gérer les cours) --> (supprimer un cours)
(gérer les cours) --> (modifier un cours)
(gérer les cours) --> (afficher un cours)
(gérer les cours) --> (inscrire un élève)
(gérer les cours) --> (désinscrire un élève)
(gérer les cours) --> (consulter les cours d'un élève)
(gérer les cours) --> (consulter les élèves d'un cours)

(gérer les adresses) --> (ajouter une adresse)
(gérer les adresses) --> (supprimer une adresse)
(gérer les adresses) --> (modifier une adresse)
(gérer les adresses) --> (afficher une adresse)

}
@enduml